### ISSUE TITLE
attach 실패

### ISSUE THREAD

**Issue by vavazz** [cocoapi/MemoryCheck#4]
![image](https://user-images.githubusercontent.com/32236838/33240264-d9405114-d2f6-11e7-9773-d684e74297a8.png)

**Comment by vavazz** [comment]
ios는 붙엇다고 나오지만 main program에서는 다음 메뉴로 진행 불가

**Comment by vavazz** [comment]
프로그램 종료후 프로세스 gdb6는 여전히 남아있음

![image](https://user-images.githubusercontent.com/32236838/33240410-cbcbc778-d2f8-11e7-93ba-83093034f5a5.png)

**Comment by cocoapi** [comment]
이슈 닫지마세요...
일단 좀 있다가 그부분 확인해볼게요

**Comment by cocoapi** [comment]
gdb attach이슈 해결
